/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 droneOne.gltf 
Author: 3DHaupt (https://sketchfab.com/dennish2010)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
Source: https://sketchfab.com/3d-models/drone-design-592c49fb806c42dba309e4d7a31d4a57
Title: Drone Design
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('./droneOne.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null} >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Root">
            <group name="helicopter_box" position={[0, 0.079, 0.099]}>
              <mesh name="helicopter_box_0" geometry={nodes.helicopter_box_0.geometry} material={materials.Hely} />
            </group>
            <group name="Plane" position={[0, 0, 0.037]} scale={[0.529, 0.429, 0.429]}>
              <mesh name="Plane_0" geometry={nodes.Plane_0.geometry} material={materials.material}/>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/droneOne.gltf')
